apiVersion: v1
kind: ConfigMap
metadata:
  name: orquidea-config
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://mysql-service:3306/orquidea
    spring.datasource.username=root
    management.endpoint.health.show-details=always
    management.endpoints.web.exposure.include=*
    management.endpoint.health.probes.enabled=true
    server.port=8080
---
apiVersion: v1
kind: Secret
metadata:
  name: orquidea-secrets
type: Opaque
data:
  # El valor debe estar en base64: echo -n "tupassword" | base64
  db-password: cm9vdA==  # 'root' en base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orquidea-express-api
  labels:
    app: orquidea-express-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orquidea-express-api
  template:
    metadata:
      labels:
        app: orquidea-express-api
    spec:
      containers:
      - name: orquidea-express-api
        image: orquidea-express-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orquidea-secrets
              key: db-password
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: orquidea-config
---
apiVersion: v1
kind: Service
metadata:
  name: orquidea-express-api-service
spec:
  type: NodePort
  selector:
    app: orquidea-express-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000